spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vermapv749@gmail.com
    password: susj ahoe ygjk honx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  datasource:
    url: jdbc:mysql://localhost:3306/lms?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Prashant@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false